host: "127.0.0.1"
port: "9871"
password: "my_password"
commands:
  - 0:
    name: "mute discord"
    display_name: "Mic Mute Discord"
    buttons: ["m"]
    shift: false
    rshift: false
    ctrl: true
    rctrl: false
    alt: true
    ralt: false
  - 1:
    name: "deaf discord"
    display_name: "Audio Mute Discord"
    buttons: ["n"]
    shift: false
    rshift: false
    ctrl: true
    rctrl: false
    alt: true
    ralt: false
  - 2:
    name: "prestazioni"
    display_name: "Prestazioni AMD"
    buttons: ["o"]
    shift: true
    rshift: false
    ctrl: true
    rctrl: false
    alt: false
    ralt: false
