host: "127.0.0.1"
port: "9871"
password: "my_password"
commands:
  - 0:
    name: "mute discord"
    buttons: ["m"]
    shift: false
    rshift: false
    ctrl: true
    rctrl: false
    alt: true
    ralt: false
  - 1:
    name: "deaf discord"
    buttons: ["n"]
    shift: false
    rshift: false
    ctrl: true
    rctrl: false
    alt: true
    ralt: false

